name: "Git AI PR Viewer"
description: "Upload AI-assisted diff data for pull requests"
author: "acunniffe"
branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  git-ai-version:
    description: "Version of git-ai to install (e.g., 'v1.0.23'). Defaults to latest release."
    required: false
    default: "latest"
  git-ai-repo:
    description: "GitHub repo to download git-ai from (owner/repo format)."
    required: false
    default: "acunniffe/git-ai"
  github-token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
 

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: git-ai-ci-clone
        fetch-depth: 0

    - name: Install git-ai
      shell: bash
      run: |
        VERSION="${{ inputs.git-ai-version }}"
        REPO="${{ inputs.git-ai-repo }}"
        if [ "$VERSION" = "latest" ]; then
          VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | jq -r '.tag_name')
        fi

        INSTALL_URL="https://github.com/${REPO}/releases/download/${VERSION}/install.sh"
        HTTP_STATUS=$(curl -fsSL -w "%{http_code}" -o /tmp/install.sh "$INSTALL_URL" 2>/dev/null || echo "000")

        if [ "$HTTP_STATUS" != "200" ]; then
          echo "Error: Failed to download install.sh for version ${VERSION}"
          exit 1
        fi

        bash /tmp/install.sh
        rm /tmp/install.sh
        echo "$HOME/.git-ai/bin" >> $GITHUB_PATH

        curl -fsSL https://git-ai-otel.s3.us-east-2.amazonaws.com/git-ai-otel-latest.tar.gz -o git-ai-otel.tar.gz
        tar -xzf git-ai-otel.tar.gz
        chmod +x git-ai-otel
        sudo mv git-ai-otel /usr/local/bin/

    - name: Upload AI diff for PR
      shell: bash
      working-directory: git-ai-ci-clone
      env:
        GH_TOKEN: ${{ inputs.github-token }}
       
      run: |
        git fetch origin

        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.event.repository.name }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        PR_URL="${{ github.event.pull_request.html_url }}"

        # Fetch PR metadata using gh cli
        PR_METADATA=$(gh pr view "$PR_NUMBER" --json title,author,labels,createdAt,updatedAt,baseRefName,headRefName,additions,deletions,changedFiles)

        echo "Uploading AI diff for PR #${PR_NUMBER}"
        echo "Base SHA: ${BASE_SHA}"
        echo "Head SHA: ${HEAD_SHA}"

        # Run upload-ai-diff and capture the URL
        DIFF_URL=$(git-ai-otel upload-ai-diff \
          "$BASE_SHA" \
          "$HEAD_SHA" \
          "$OWNER" \
          "$REPO" \
          "$PR_NUMBER" \
          "$PR_URL" \
          "$PR_METADATA")

        echo "AI Diff URL: ${DIFF_URL}"

        # Get current PR body
        PR_BODY=$(gh pr view "$PR_NUMBER" --json body -q '.body')

        # Check if the marker already exists
        if ! echo "$PR_BODY" | grep -q "<!-- git-ai-project/actions -->"; then
          # Append the AI diff link block to PR description
          NEW_BODY="${PR_BODY}

<!-- git-ai-project/actions -->
---
[See which lines were written by AI](${DIFF_URL}). Powered by [Git AI](https://github.com/acunniffe/git-ai)
<!-- git-ai-project/actions -->"

          gh pr edit "$PR_NUMBER" --body "$NEW_BODY"
          echo "Updated PR description with AI diff link"
        else
          echo "PR description already contains AI diff link, skipping update"
        fi
